In [1]:
import pandas as pd

data = {
    "Patient_ID": [101,102,103,104,105,106,107,108,109,110],
    "Age": [25,45,35,60,50,28,65,40,55,30],
    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],
    "Department": ["Cardiology","Neurology","Cardiology","Orthopedic",
                   "Neurology","Cardiology","Orthopedic","Neurology",
                   "Cardiology","Orthopedic"],
    "City": ["Nagpur","Pune","Nagpur","Mumbai","Pune",
             "Nagpur","Mumbai","Pune","Nagpur","Mumbai"],
    "Treatment_Cost": [50000,35000,60000,45000,30000,
                       55000,70000,40000,65000,50000],
    "Hospital_Stay": [5,3,6,4,2,5,7,3,6,4]
}

df = pd.DataFrame(data)

In [2]:
df_duplicate =pd.concat([df,df.iloc[[2,5]]],ignore_index=True)#duplicate value banana # concate fuction jodne ka kam krtaq hain
df_duplicate

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0          101   25    Male  Cardiology  Nagpur           50000              5
1          102   45  Female   Neurology    Pune           35000              3
2          103   35    Male  Cardiology  Nagpur           60000              6
3          104   60  Female  Orthopedic  Mumbai           45000              4
4          105   50    Male   Neurology    Pune           30000              2
5          106   28  Female  Cardiology  Nagpur           55000              5
6          107   65    Male  Orthopedic  Mumbai           70000              7
7          108   40  Female   Neurology    Pune           40000              3
8          109   55    Male  Cardiology  Nagpur           65000              6
9          110   30  Female  Orthopedic  Mumbai           50000              4
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5

In [3]:
#pd.concate()#data frame ko jodne ka kam krta hain
#iloc[[2,5]] row 2 our row select karna:
#ignore_index = True --> index ko fresh numbering dega

In [4]:
#agar dataframe main 10 rows hain our hum df.iloc[[2,5]]se 2nd row our add kar rahe hain to total row kitni hogi
# answer :12 rows 
#aur konsi row duplicate hogi ?
# answer:patientsID-103  , patientsID-106

In [5]:
#“Imagine karo hospital ke database mein Patient 103 ka same record do baar aa gaya.
#Ab hospital ke total patients count karenge to kya hoga
df_duplicate

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0          101   25    Male  Cardiology  Nagpur           50000              5
1          102   45  Female   Neurology    Pune           35000              3
2          103   35    Male  Cardiology  Nagpur           60000              6
3          104   60  Female  Orthopedic  Mumbai           45000              4
4          105   50    Male   Neurology    Pune           30000              2
5          106   28  Female  Cardiology  Nagpur           55000              5
6          107   65    Male  Orthopedic  Mumbai           70000              7
7          108   40  Female   Neurology    Pune           40000              3
8          109   55    Male  Cardiology  Nagpur           65000              6
9          110   30  Female  Orthopedic  Mumbai           50000              4
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5

In [6]:
#duplicated() duplicate hain ya nhi ye dekhne ke liye hote hain
df_duplicate.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [7]:
#sirf duplicate row dekhani hain
df_duplicate[df_duplicate.duplicated()]

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5

In [8]:
#duplicate data hatana hain
df_clean=df_duplicate.drop_duplicates()

In [9]:
df_clean

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

In [10]:
df_clean.shape

(10, 7)

In [11]:
#1)duplicated()                                       2) drop_duplicate()
#duplicate identify karta hain                       duplicate ko remove krta hain

In [12]:
# agar patients 103 2 bar hain to kya 2 record honge kya
df_duplicate.duplicated(subset="Patient_ID")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [13]:
df_duplicate.drop_duplicates(subset=["Patient_ID"])

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

In [ ]:




#“Agar hospital ke patient records mein duplicate entries hain aur hum unhe remove nahi karte, to patient count aur department-wise analysis par kya effect padega?”
#Expected thinking:
#Patient count wrong → Department count wrong → Cost analysis bhi wrong ho sakta hai.

In [ ]:
#Duplicate rows identify karo:
print(df.duplicated().sum()) 
df[df.duplicated()]

0

Empty DataFrame
Columns: [Patient_ID, Age, Gender, Department, City, Treatment_Cost, Hospital_Stay]
Index: []

In [ ]:
#Duplicate remove karo:
df=df.drop_duplicates()

In [ ]:
#Before/After rows compare karo:
print(f"Before:{df.shape}")
df=df.drop_duplicates()
print(f"After:{df.shape}")

Before:(10, 7)
After:(10, 7)